basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: mir100_1
    name: MiR100-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.mir.opmodes
    executionMode: SIMULATE
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.mir.service.MirServiceImpl
        connectionString: http://robot-mir-01.mrk40.dfki.lan
        auth: bXJrOjZjNGIwNmRjYTU4NmM1NzkxYmI2Nzc4MjFjZjU3YWQ0ZjcyOGVmMTZmMWNjN2ZiMDg1MmEwNmY3Yzc5NmI1M2Y=
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true
#      service:
#        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.mir.service.MirServiceROSImpl
#        connectionString: ws://10.107.0.142:9100
#        gotoServerName: /movsym/mir100_1
#        gotoActionName: /simrk40_msgs/MoveToSymbolicPositionAction
#        pickServerName: /picksym/mir100_1
#        pickActionName: /simrk40_msgs/PickSymbolicAction
#        placeServerName: /placesym/mir100_1
#        placeActionName: /simrk40_msgs/PlaceSymbolicAction
